name: delete-submodules
author: gendloop
description: 'action description'
inputs:
  submodule_path:
    description: 'Submodule path to delete'
    required: false
    default: ''
  all:
    description: 'Delete all repos'
    required: true
    default: false
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
      with: 
        submodules: 'recursive'
        token: ${{ inputs.token }}

    - name: delete-all-submodules
      shell: bash
      working-directory: ${{ github.workspace }}
      if: ${{ inputs.all }}
      run: |
        git submodule init
        git submodule update
        folders=($(git submodule foreach --quiet 'echo $path'))
        git submodule deinit --all
        rm -rf .git/modules/
        rm .gitmodules
        for folder in "${folders[@]}"; do
          rm -rf $folder
        done

    - name: delete-specific-submodule
      shell: bash
      working-directory: ${{ github.workspace }}
      if: false == ${{ inputs.all }}
      run: |
        git submodule init
        git submodule update
        git submodule deinit ${{ inputs.submodule_path }}
        git config --file=.gitmodules --remove-section submodule.${{ inputs.submodule_path }}
        rm -rf .git/modules/${{ inputs.submodule_path }}
        rm -rf ${{ inputs.submodule_path }}

    - name: git-push-all-submodules
      uses: gendloop/git-push@v1.0.0
      if: ${{ inputs.all }}
      with:
        token: ${{ github.token }}
        commit: "chore: delete all submodules"

    - name: git-push-specific-submodule
      uses: gendloop/git-push@v1.0.0
      if: false == ${{ inputs.all }}
      with:
        token: ${{ github.token }}
        commit: "chore: delete submodule ${{ inputs.submodule_path }}"
